### ISSUE TITLE
Getting a "Duplicate definition" error when using this module in a new Vagran box

### ISSUE THREAD

**Issue by gthank** [BenoitCattie/puppet-nginx#1]
When I attempt to use this module in a new CentOS 5.5 box (virtualized, managed using Vagrant) I get the following error:

```
[default] Duplicate definition: File[undef] is already defined in file /tmp/vagrant-puppet/modules-0/nginx/manifests/init.pp at line 56; cannot redefine at /tmp/vagrant-puppet/modules-0/nginx/manifests/init.pp:72 on node centos5.vagrant.internal
```

**Comment by BenoitCattie** [comment]
I think there is something wrong in your definitions.

Can you give me the node definition for this host ?

**Comment by gthank** [comment]
The entire manifest right now is:

include nginx

I take it from your email that I'm doing this wrong. Sorry if I'm
bothering you with n00b questions. Thanks for helping.

-Hank

On Tue, May 3, 2011 at 1:17 PM, BenoitCattie
reply@reply.github.com
wrote:

**Comment by maxstepanov** [comment]
This happens because $nginx_includes and  $nginx_conf aren't defined in scope of the nginx class.
I guess, move them inside the class where they should be.

**Comment by BenoitCattie** [comment]
This issue should be fixed with the last comit
