### ISSUE TITLE
Security problem with your generated configs

### ISSUE THREAD

**Issue by mc0e** [BenoitCattie/puppet-nginx#11]
As it stands, the configs your module generates exhibit the problem described here:

  https://nealpoole.com/blog/2011/04/setting-up-php-fastcgi-and-nginx-dont-trust-the-tutorials-check-your-configuration/

In brief, any file in the server's web space can be executed as php.  Ie there's any sort of file uploads by users it becomes dangerous.  eg user uploads "picture.gif", which is in fact a php file, and then addresses it as "path/picture.gif/foo.php".

Easily fixed with a test for file existence.

**Comment by BenoitCattie** [comment]
Hi,

thanks for the repport.
I'm going to update the module to fix it

**Comment by BenoitCattie** [comment]
Fix in commit 1f574fa171cbb54118466744370e40dfac2f2c50
