### ISSUE TITLE
missing Modulefile causes puppet-module not to install module

### ISSUE THREAD

**Issue by grooverdan** [BenoitCattie/puppet-nginx#4]
$ puppet-module install BenoitCattie/nginx
Could not parse filename to obtain the username, module name and version.  (BenoitCattie-nginx-0.2)
$ ls
(nothing installed)

using puppet-module-0.3.4

**Comment by BenoitCattie** [comment]
Thanks for the report.

I m going to update nginx module to fix this issue.

Benoit

**Comment by kelseyhightower** [comment]
Benoit,

I am going to use your module for the first offical Puppet Labs module of the week! I figured it would be cool to lend you a hand and help clean things up a bit.

**Comment by kelseyhightower** [comment]
I have two more pull requests in the works, the next one splits out each defined resource into a seperate file, and the other will finish the job of converting tabs to spaces and other style guide bits.

**Comment by kelseyhightower** [comment]
Please see my Pull request, I have a fix for this already

**Comment by BenoitCattie** [comment]
Thanks a lot for your contribution.
I have few time these days.

Thanks !
