### ISSUE TITLE
Bad path for 'ln' command

### ISSUE THREAD

**Issue by darkpixel** [BenoitCattie/puppet-nginx#5]
In manifests/init.pp you have a path of '/usr/bin' when you call 'ln' to create the symlink.  Under Ubuntu, that file is in '/bin' so the command fails.  The following will fix it:

  path => ["/usr/bin/", "/bin"],

**Comment by kelseyhightower** [comment]
This issue should be resolved in my latest pull request

**Comment by BenoitCattie** [comment]
Fixed
